In [1]:
#question-1:
#vector is 1-dimensional,while a matrix is 2-dimensional


In [2]:
#question-2:
import numpy as np

In [3]:
# question-3:
import numpy as np

list_1=[1,2,3,4,5]
arr=np.array(list_1)

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [4]:
# question-4
import numpy as np

arr=np.arange(0,6)
print(arr)


[0 1 2 3 4 5]


In [5]:
# question-5:
import numpy as np
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [6]:
# question-6:
import numpy as np

mat=np.zeros((3,4))
print(mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# question-7:
import numpy as np

arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [8]:
# question-8:
import numpy as np

arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [9]:
# question-9:
import numpy as np

evens=np.arange(50,101,2)
print(evens)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


In [10]:
# question-10:
import numpy as np

evens=np.arange(50,101,2)
print(evens)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


In [11]:
# question-11:
import numpy as np

evens=np.arange(50,101,2)
print(evens)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


In [12]:
import numpy as np

evens=np.arange(50,101,2)
print(evens)


[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


In [13]:
# yes, we can use shape instead of reshape as well.
import numpy as np

vec = np.arange(25)
vec.shape = (5,5)

print("Vector:", vec)

Vector: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
# question-12:
# yes, we can use shape instead of reshape as well.
import numpy as np

vec = np.arange(25)
vec.shape = (5,5)

print("Vector:", vec)

Vector: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
# question-13:
# yes, we can use shape instead of reshape as well.
import numpy as np

vec = np.arange(25)
vec.shape = (5,5)

print("Vector:", vec)

Vector: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
# question-14:
# yes, we can use shape instead of reshape as well.
import numpy as np

vec = np.arange(25)
vec.shape = (5,5)

print("Vector:", vec)

Vector: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [17]:
# question-15:
# yes, we can use shape instead of reshape as well.
import numpy as np

vec = np.arange(25)
vec.shape = (5,5)

print("Vector:", vec)

Vector: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [18]:
# question-16:
# yes, we can use shape instead of reshape as well.
import numpy as np

vec = np.arange(25)
vec.shape = (5,5)

print("Vector:", vec)

Vector: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [19]:
# question-17:
# yes, we can use shape instead of reshape as well.
import numpy as np

vec = np.arange(25)
vec.shape = (5,5)

print("Vector:", vec)

Vector: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
